### PR TITLE
Update homework.sh

### PR DESCRIPTION
**Pull request by Navneettc**
## @mentions of the person or team responsible for reviewing proposed changes (At least 2 people)
-
 @Michaeladrouillard 
@dtxe 
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by Navneettc** [comment]
> ## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
> ## What did you learn from the changes you have made?
> ## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
> ## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
> ## How were these changes tested?
> ## A reference to a related issue in your repository (if applicable)
> ## @mentions of the person or team responsible for reviewing proposed changes (At least 2 people)
> 
> ## Checklist
> * [ ]  I can confirm that my changes are working as intended

@michalea

**Comment by Navneettc** [comment]
@Michaeladrouillard

**Comment by Navneettc** [comment]
> ## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
> ## What did you learn from the changes you have made?
> ## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
> ## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
> ## How were these changes tested?
> ## A reference to a related issue in your repository (if applicable)
> ## @mentions of the person or team responsible for reviewing proposed changes (At least 2 people)
> 
> ## Checklist
> * [ ]  I can confirm that my changes are working as intended

**Comment by dwz92** [comment]
Please review comments from https://github.com/UofT-DSI/shell/pull/51

**Pull request closed without merging**
